name: Build Library

on:
    push:
        branches:
            - main
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Build library
              run: npm run build

            - name: Bundle index.js and its imports
              run: npm run bundle-index

            - name: Upload bundled file as artifact
              uses: actions/upload-artifact@v2
              with:
                  name: bundled-library
                  path: dist/index.bundle.js

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false
                  files: |
                      dist/index.bundle.js  # Add more files if needed
