name: Build Canary Library

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Build library
              run: npm run build

            - name: Read version from package.json using npm
              id: version
              run: |
                  VERSION=$(npm pkg get version)
                  VERSION=$(echo $VERSION | sed -e 's/^"//' -e 's/"$//')
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Upload bundled file as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: bundled-library
                  path: bundle.js

            - name: Create GitHub Release
              uses: ncipollo/release-action@v1.14.0
              with:
                  name: ascii.js v${{ env.VERSION }}-canary
                  tag: v${{ env.VERSION }}-canary
                  artifacts: "bundle.js"
